services:

  postgres:
    image: postgres:15
    container_name: carteblanche_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: carteblanche
    ports:
      - "5433:5432"
    volumes:
      - carteblanche_data:/var/lib/postgresql/data

  streamlit:
    build: .
    container_name: carteblanche_app
    ports:
      - "8505:8501"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./data:/app/data

volumes:
  carteblanche_data: